spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ssgdb
    username: ssg_user
    password:
    sql-script-encoding: utf-8
  jpa :
    database-platform : org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true


server:
  port: 5555
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
